import {
  getOwnerUid,
  json,
  query,
  rateLimitOk,
  toBoard,
  type BoardRow,
} from "../_db.js";

/**
 * Collection endpoint: list and create boards.
 *
 * Pins the Node.js runtime so `vercel dev` and production behave identically
 * (see `api/health.ts` for why this is explicit).
 */
export const config = { runtime: "nodejs" };

/**
 * Columns safe to send to a listing.
 *
 * `scene` is deliberately absent: `listBoards` strips it in the Dexie version
 * too, because scenes can be megabytes and the grid never renders them. Use
 * `GET /api/boards/[id]` when you need it. `scene_bytes` *is* included, because
 * it is what lets the "size" sort work without loading scenes
 * (`selectors.ts:41`).
 */
const LIST_COLUMNS = `id, name, folder_id, favorite, trashed_at, thumbnail,
  scene_version, created_at, updated_at, last_opened_at, scene_bytes`;

/**
 * `GET /api/boards`
 *
 * Query parameters mirror `listBoards` in `db/operations.ts` so the API adapter
 * in STEP 4 can be a drop-in replacement for the Dexie one:
 *
 * - `trashed=1` -> only soft-deleted boards (the trash page). Default is live
 *   boards only, which is what `listBoards` does with `includeTrashed: false`.
 * - `folderId=<uuid>` -> boards in that folder. `folderId=unfiled` selects
 *   boards with no folder, matching `selectors.ts`'s "null means unfiled".
 *
 * Ordering is `COALESCE(last_opened_at, updated_at) DESC`, which is the app's
 * actual "recent" sort (`selectors.ts:47`) rather than just `updated_at` — a
 * board that was opened but not edited should still sort as recently used.
 *
 * Every query is scoped by `owner_uid`, so one owner can never read another's
 * rows regardless of the id they pass.
 */
const handleGet = async (
  req: Request,
  url: URL,
  uid: string,
  cookie: Headers,
) => {
  const trashed = url.searchParams.get("trashed") === "1";
  const folderParam = url.searchParams.get("folderId");

  const rows =
    folderParam === null
      ? await query<BoardRow>(
          `SELECT ${LIST_COLUMNS} FROM boards
         WHERE owner_uid = $1 ${
           trashed ? "AND trashed_at IS NOT NULL" : "AND trashed_at IS NULL"
         }
         ORDER BY COALESCE(last_opened_at, updated_at) DESC`,
          [uid],
        )
      : folderParam === "unfiled"
      ? await query<BoardRow>(
          `SELECT ${LIST_COLUMNS} FROM boards
           WHERE owner_uid = $1 AND folder_id IS NULL
             ${
               trashed ? "AND trashed_at IS NOT NULL" : "AND trashed_at IS NULL"
             }
           ORDER BY COALESCE(last_opened_at, updated_at) DESC`,
          [uid],
        )
      : await query<BoardRow>(
          `SELECT ${LIST_COLUMNS} FROM boards
           WHERE owner_uid = $1 AND folder_id = $2
             ${
               trashed ? "AND trashed_at IS NOT NULL" : "AND trashed_at IS NULL"
             }
           ORDER BY COALESCE(last_opened_at, updated_at) DESC`,
          [uid, folderParam],
        );

  return json({ boards: rows.map(toBoard) }, 200, cookie);
};

/**
 * `POST /api/boards`
 *
 * Creates a board and returns it with its server-assigned `id`, mirroring
 * `createBoard` in `db/operations.ts`: `favorite`, `trashedAt` and
 * `lastOpenedAt` start false/null, `sceneVersion` starts at 0, and `name`
 * defaults to "Untitled board" so the "New board" button does not have to invent
 * one.
 *
 * The `activity` insert is the reason the table exists: `getBoardStatsMap`
 * (`db/operations.ts:415`) counts those rows for the card chip, and the Activity
 * page renders them as a timeline. Skipping it would leave both permanently
 * empty.
 *
 * `folderId` is validated against the caller's own folders rather than left to
 * the foreign key. The FK would happily accept another owner's folder uuid, which
 * would silently leak that folder's name into the sidebar.
 */
const handlePost = async (req: Request, uid: string, cookie: Headers) => {
  let body: Record<string, unknown>;
  try {
    body = (await req.json()) as Record<string, unknown>;
  } catch {
    return json({ error: "invalid JSON body" }, 400, cookie);
  }

  const name =
    typeof body.name === "string" && body.name.trim()
      ? body.name.trim()
      : "Untitled board";
  const folderId =
    typeof body.folderId === "string" && body.folderId ? body.folderId : null;
  const thumbnail = typeof body.thumbnail === "string" ? body.thumbnail : null;
  const scene = typeof body.scene === "string" ? body.scene : null;
  const sceneBytes = scene === null ? null : scene.length;

  if (folderId !== null) {
    const owned = await query(
      "SELECT 1 FROM folders WHERE id = $1 AND owner_uid = $2",
      [folderId, uid],
    );
    if (owned.length === 0) {
      return json({ error: "folder not found" }, 404, cookie);
    }
  }

  // id is generated by Postgres (gen_random_uuid()) so the client never has to
  // invent a uuid, and the ledger row is written in the same statement batch so a
  // created board always has a matching audit entry.
  const inserted = await query<BoardRow>(
    `INSERT INTO boards (owner_uid, name, folder_id, thumbnail, scene, scene_bytes)
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING ${LIST_COLUMNS}, scene`,
    [uid, name, folderId, thumbnail, scene, sceneBytes],
  );

  const board = toBoard(inserted[0]);
  await query(
    "INSERT INTO activity (owner_uid, board_id, type) VALUES ($1, $2, 'create')",
    [uid, board.id],
  );

  return json({ board }, 201, cookie);
};

export default async function handler(req: Request): Promise<Response> {
  // Placeholder response whose headers `getOwnerUid` appends the uid cookie to;
  // the real response is built with those headers once the work is done.
  const cookie = new Headers();

  try {
    const uid = getOwnerUid(req, cookie);

    if (!rateLimitOk(uid)) {
      return json({ error: "rate limit exceeded" }, 429, cookie);
    }

    const url = new URL(req.url);

    if (req.method === "GET") {
      return await handleGet(req, url, uid, cookie);
    }
    if (req.method === "POST") {
      return await handlePost(req, uid, cookie);
    }

    // Allow the browser client to discover the methods this route supports.
    if (req.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: cookie });
    }

    return json({ error: "method not allowed" }, 405, cookie);
  } catch (error) {
    // Log the real cause server-side; return an opaque 500. Driver errors can
    // contain the connection URL, which must never reach a client.
    console.error("[api/boards]", error);
    return json({ error: "internal error" }, 500, cookie);
  }
}
